export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_USER_WINS = "SET_USER_WINS";
export const SET_USER_LOSSES = "SET_USER_LOSSES";
export const SET_USER_WIN_PERCENTAGE = "SET_USER_WIN_PERCENTAGE";
export const ADD_NEW_PICK = "ADD_NEW_PICK";
export const GET_LEADERBOARD = "GET_LEADERBOARD";
